model_parameters:
  encoder:
    embedding_dimension: 1024
    patch_size: 4
    num_channels: 128
    depth: 12
    num_heads: 8
    mlp_ratio: 4
    qkv_bias: True
  decoder:
    embedding_dimension: 1024
    patch_size: 4
    num_channels: 128
    depth: 6
    num_heads: 4
    mlp_ratio: 1.0
    qkv_bias: True
  dropout: 0.2

logging:
  log_level: INFO
  log_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  log_file: auto_encoder.log
  log_file_mode: 'w'
  log_file_level: INFO
  log_steps: 20
checkpoint:
  checkpoint_dir: /mnt/a/MainFolder/Neural Nirvana/encoder_transformer/model_copy/EEG/auto_encoder/logs/checkpoints
  checkpoint_filename_base: /mnt/a/MainFolder/Neural Nirvana/encoder_transformer/model_copy/EEG/auto_encoder/logs/checkpoints/auto_encoder
  checkpoint_path: /mnt/a/MainFolder/Neural Nirvana/encoder_transformer/model_copy/EEG/auto_encoder/logs/checkpoints
  load_checkpoint: False


training_parameters:
  num_epochs: 350
  batch_size: 16
  device: cuda
  warmup_epochs: 40

optimizer:
  optimizer: Adam
  optimizer_parameters:
    lr: 2.5e-4
    weight_decay: 0.0001
    betas: [0.9, 0.999]
    eps: 1e-08
    amsgrad: False
    min_lr: 0
    clip_grad: 0.8

scheduler:
  scheduler: StepLR
  scheduler_parameters:
    step_size: 30
    gamma: 0.1

misc:
  local_rank: 0
  seed: 42
  participant_sub_groups: [
        [1], [2], [3, 4, 5, 6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
    ]
  plot_dir: /mnt/a/MainFolder/Neural Nirvana/encoder_transformer/model_copy/EEG/auto_encoder/logs/reconstructions
  mask_ratio: 0.75

